### PR TITLE
Adds 2 english WP podcasts

### PR DESCRIPTION
**Pull request by Soean**

### CODE REVIEW

**Comment by obstschale** [comment]
Nice one :+1: 

Does the "The JavaScript for WordPress Show" not have a website? I would rather link to the website than to iTunes.

**Comment by Soean** [comment]
There are episode pages like: https://javascriptforwp.com/show/ep-6-learning-js-like-hacker-weston-ruter/, but I couldn't find an overview page. https://javascriptforwp.com/show shows only the youtube videos, not the posts with audio. Should we just link to https://javascriptforwp.com ?

**Comment by obstschale** [comment]
That is weird. Maybe we should tell that Zac. He should at least link to some page where people could find the episodes and podcast links.

**Comment by obstschale** [comment]
I merged your PR and I will get in contact with Zac. Thx so far :+1:

**Comment by Soean** [comment]
Thanks, I asked him on Twitter, something is broken: https://twitter.com/zgordon/status/900838780835377153

**Comment by obstschale** [comment]
Can you send a new PR with the correct link when he fixed it?

**Comment by obstschale** [comment]
:man_facepalming: I didn't see that you already sent another PR.

**Pull request merged**
